import { lazy } from 'react';
import { Building } from 'lucide-react';
import type { ModuleManifest } from '../_types';

const NLExchangeModule = lazy(() => import('./NLExchangeModule'));

export const manifest: ModuleManifest = {
  id: 'nl-stabu-exchange',
  name: 'Netherlands STABU Exchange',
  description: 'Import/export BOQs in Dutch STABU / RAW format (Excel/CSV)',
  version: '1.0.0',
  icon: Building,
  category: 'regional',
  defaultEnabled: false,
  depends: ['boq'],
  routes: [
    {
      path: '/nl-stabu-exchange',
      title: 'Netherlands STABU Exchange',
      component: NLExchangeModule,
    },
  ],
  // Issue #217 — reached from /boq (regional import/export); no duplicate sidebar entry.
  navItems: [],
  searchEntries: [
    {
      label: 'Netherlands STABU Import / Export',
      path: '/nl-stabu-exchange',
      keywords: [
        'netherlands',
        'dutch',
        'nederland',
        'belgium',
        'belgie',
        'stabu',
        'raw',
        'besteksystematiek',
        'bouwkosten',
        'eur',
      ],
    },
  ],
  translations: {
    en: {
      'nav.nl_stabu_exchange': 'Netherlands STABU Exchange',
      'nl.title': 'Netherlands STABU Import / Export',
      'nl.subtitle': 'Exchange Bills of Quantities in STABU / RAW format (Excel / CSV)',
      'nl.tab_import': 'Import',
      'nl.tab_export': 'Export',
      'nl.import_complete': 'Dutch STABU BOQ import complete',
      'nl.export_complete': 'Dutch STABU BOQ export complete',
      'nl.info': 'STABU (Standaard Besteksystematiek voor de Bouw) is the Dutch standard classification for construction specifications. RAW (Rationalisatie en Automatisering Grond-, Water- en Wegenbouw) covers civil engineering works. Compatible with BouwKosten online, CROW standards, and Belgian VMSW practices.',
      'nl.drop_file': 'Drop a Dutch STABU/RAW BOQ file here (Excel or CSV), or',
      'nl.browse': 'Browse files',
      'nl.formats_hint': 'Supported: .csv, .tsv, .xlsx (STABU/RAW-formatted BOQ)',
      'nl.classification': 'STABU Chapter',
      'nl.export_format': 'Format',
      'nl.csv_format': 'CSV (Excel-compatible)',
      'nl.detailed': 'STABU Detailed',
      'nl.summary': 'STABU Summary',
      'nl.preview': 'Preview',
      'nl.positions': 'positions',
      'nl.positions_found': 'positions found',
      'nl.show_less': 'Show less',
      'nl.show_all': 'Show all',
      'nl.target_boq': 'Import Target',
      'nl.select_boq': 'Select BOQ',
      'nl.importing': 'Importing...',
      'nl.import_btn': 'Import positions',
      'nl.import_failed': 'Dutch STABU import failed',
      'nl.positions_imported': 'positions imported',
      'nl.parsed_ok': 'File parsed successfully',
      'nl.parse_error': 'No positions found in the file. Ensure the file is a valid STABU/RAW-formatted BOQ (CSV, TSV, or XLSX).',
      'nl.parse_error_generic': 'Failed to parse the Dutch STABU BOQ file.',
      'nl.source_boq': '1. Select BOQ to Export',
      'nl.export_summary': '2. Export Summary',
      'nl.hide_preview': 'Hide preview',
      'nl.show_preview': 'Show preview',
      'nl.sections': 'Sections',
      'nl.format_label': 'Format',
      'nl.prices_label': 'Prices',
      'nl.export_btn': 'Export as STABU CSV',
      'nl.export_failed': 'Dutch STABU export failed',
      'nl.no_positions': 'This BOQ has no positions to export.',
      'nl.print_btn': 'Print / PDF',
      'nl.trades_ref': 'STABU Chapter Reference',
      'nl.with_prices': 'with prices',
      'nl.no_prices': 'quantities only',
    },
    nl: {
      'nav.nl_stabu_exchange': 'Nederland STABU Uitwisseling',
      'nl.title': 'Nederland STABU Import / Export',
      'nl.subtitle': 'Hoeveelheidstaten uitwisselen in STABU / RAW-formaat (Excel / CSV)',
      'nl.tab_import': 'Importeren',
      'nl.tab_export': 'Exporteren',
      'nl.import_complete': 'STABU-import voltooid',
      'nl.export_complete': 'STABU-export voltooid',
      'nl.info': 'STABU (Standaard Besteksystematiek voor de Bouw) is de Nederlandse standaard classificatie voor bouwspecificaties. RAW (Rationalisatie en Automatisering Grond-, Water- en Wegenbouw) dekt civiele techniek. Compatibel met BouwKosten online, CROW-standaarden en Belgische VMSW-praktijken.',
      'nl.drop_file': 'Sleep een STABU/RAW-bestand hierheen (Excel of CSV), of',
      'nl.browse': 'Bladeren',
      'nl.formats_hint': 'Ondersteund: .csv, .tsv, .xlsx (STABU/RAW-geformatteerd)',
      'nl.classification': 'STABU Hoofdstuk',
      'nl.export_format': 'Formaat',
      'nl.csv_format': 'CSV (Excel-compatibel)',
      'nl.detailed': 'STABU Gedetailleerd',
      'nl.summary': 'STABU Samenvatting',
      'nl.preview': 'Voorbeeld',
      'nl.positions': 'posten',
      'nl.positions_found': 'posten gevonden',
      'nl.show_less': 'Minder tonen',
      'nl.show_all': 'Alles tonen',
      'nl.target_boq': 'Importdoel',
      'nl.select_boq': 'Selecteer bestek',
      'nl.importing': 'Importeren...',
      'nl.import_btn': 'Posten importeren',
      'nl.import_failed': 'STABU-import mislukt',
      'nl.positions_imported': 'posten geimporteerd',
      'nl.parsed_ok': 'Bestand succesvol verwerkt',
      'nl.parse_error': 'Geen posten gevonden in het bestand. Controleer of het bestand een geldig STABU/RAW-bestek is (CSV, TSV of XLSX).',
      'nl.parse_error_generic': 'Kan het STABU-bestand niet verwerken.',
      'nl.source_boq': '1. Selecteer bestek om te exporteren',
      'nl.export_summary': '2. Exportoverzicht',
      'nl.hide_preview': 'Voorbeeld verbergen',
      'nl.show_preview': 'Voorbeeld tonen',
      'nl.sections': 'Secties',
      'nl.format_label': 'Formaat',
      'nl.prices_label': 'Prijzen',
      'nl.export_btn': 'Exporteren als STABU CSV',
      'nl.export_failed': 'STABU-export mislukt',
      'nl.no_positions': 'Dit bestek heeft geen posten om te exporteren.',
      'nl.print_btn': 'Afdrukken / PDF',
      'nl.trades_ref': 'STABU Hoofdstukken Referentie',
      'nl.with_prices': 'met prijzen',
      'nl.no_prices': 'alleen hoeveelheden',
    },
    de: {
      'nav.nl_stabu_exchange': 'Niederlande STABU Austausch',
      'nl.title': 'Niederlande STABU Import / Export',
      'nl.subtitle': 'Leistungsverzeichnis im STABU/RAW-Format austauschen (Excel / CSV)',
      'nl.tab_import': 'Importieren',
      'nl.tab_export': 'Exportieren',
      'nl.import_complete': 'Niederlaendischer STABU-Import abgeschlossen',
      'nl.export_complete': 'Niederlaendischer STABU-Export abgeschlossen',
    },
    ru: {
      'nav.nl_stabu_exchange': 'Niderlandy STABU Obmen',
      'nl.title': 'Niderlandy STABU Import / Eksport',
      'nl.subtitle': 'Obmen dannymi smety v formate STABU / RAW (Excel / CSV)',
      'nl.tab_import': 'Import',
      'nl.tab_export': 'Eksport',
      'nl.import_complete': 'Import STABU zavershen',
      'nl.export_complete': 'Eksport STABU zavershen',
    },
  },
};
