import { lazy } from 'react';
import { Euro } from 'lucide-react';
import type { ModuleManifest } from '../_types';

const ESExchangeModule = lazy(() => import('./ESExchangeModule'));

export const manifest: ModuleManifest = {
  id: 'es-pbc-exchange',
  name: 'Spain PBC Exchange',
  description: 'Import/export BOQs in Spanish PBC / Base de Precios format (Excel/CSV)',
  version: '1.0.0',
  icon: Euro,
  category: 'regional',
  defaultEnabled: false,
  depends: ['boq'],
  routes: [
    {
      path: '/es-pbc-exchange',
      title: 'Spain PBC Exchange',
      component: ESExchangeModule,
    },
  ],
  // Issue #217 — reached from /boq (regional import/export); no duplicate sidebar entry.
  navItems: [],
  searchEntries: [
    {
      label: 'Spain PBC Import / Export',
      path: '/es-pbc-exchange',
      keywords: [
        'spain',
        'spanish',
        'españa',
        'pbc',
        'presupuesto',
        'base de precios',
        'mediciones',
        'capítulo',
        'partida',
        'eur',
      ],
    },
  ],
  translations: {
    en: {
      'nav.es_pbc_exchange': 'Spain PBC Exchange',
      'es.title': 'Spain PBC / Base de Precios Import / Export',
      'es.subtitle':
        'Exchange Bills of Quantities in Spanish PBC / Base de Precios format (Excel / CSV)',
      'es.tab_import': 'Import',
      'es.tab_export': 'Export',
      'es.import_complete': 'Spanish PBC import complete',
      'es.export_complete': 'Spanish PBC export complete',
      'es.info':
        'PBC (Presupuesto y Base de Costes) and Base de Precios de la Construccion are the standard Spanish cost reference systems. BOQs are organized by Capitulos (chapters) and Partidas (items) following the structure of the Codigo Tecnico de la Edificacion (CTE). Compatible with Presto, Arquimedes, and Spanish public procurement (LCSP) requirements.',
      'es.drop_file': 'Drop a Spanish PBC file here (Excel or CSV), or',
      'es.browse': 'Browse files',
      'es.formats_hint': 'Supported: .csv, .tsv, .xlsx (PBC-formatted BOQ)',
      'es.classification': 'PBC Chapter',
      'es.export_format': 'Format',
      'es.csv_format': 'CSV (Excel-compatible)',
      'es.pbc_detailed': 'PBC Detailed',
      'es.pbc_summary': 'PBC Summary',
      'es.preview': 'Preview',
      'es.positions': 'positions',
      'es.positions_found': 'positions found',
      'es.show_less': 'Show less',
      'es.show_all': 'Show all',
      'es.target_boq': 'Import Target',
      'es.select_boq': 'Select BOQ',
      'es.importing': 'Importing...',
      'es.import_btn': 'Import positions',
      'es.import_failed': 'PBC import failed',
      'es.positions_imported': 'positions imported',
      'es.parsed_ok': 'File parsed successfully',
      'es.parse_error':
        'No positions found in the file. Ensure the file is a valid PBC spreadsheet (CSV or Excel).',
      'es.parse_error_generic': 'Failed to parse the PBC file.',
      'es.source_boq': '1. Select BOQ to Export',
      'es.export_summary': '2. Export Summary',
      'es.hide_preview': 'Hide preview',
      'es.show_preview': 'Show preview',
      'es.sections': 'Sections',
      'es.format_label': 'Format',
      'es.prices_label': 'Prices',
      'es.export_btn': 'Export as PBC CSV',
      'es.export_failed': 'PBC export failed',
      'es.no_positions': 'This BOQ has no positions to export.',
      'es.print_btn': 'Print / PDF',
      'es.trades_ref': 'PBC Chapters Reference',
      'es.with_prices': 'with prices',
      'es.no_prices': 'quantities only',
    },
    es: {
      'nav.es_pbc_exchange': 'Intercambio PBC Espana',
      'es.title': 'PBC / Base de Precios Importar / Exportar',
      'es.subtitle':
        'Intercambio de mediciones y presupuestos en formato PBC / Base de Precios (Excel / CSV)',
      'es.tab_import': 'Importar',
      'es.tab_export': 'Exportar',
      'es.import_complete': 'Importacion PBC completada',
      'es.export_complete': 'Exportacion PBC completada',
      'es.info':
        'PBC (Presupuesto y Base de Costes) y Base de Precios de la Construccion son los sistemas de referencia de costes estandar en Espana. Los presupuestos se organizan por Capitulos y Partidas siguiendo la estructura del Codigo Tecnico de la Edificacion (CTE). Compatible con Presto, Arquimedes y requisitos de contratacion publica (LCSP).',
      'es.drop_file': 'Suelte un archivo PBC aqui (Excel o CSV), o',
      'es.browse': 'Examinar archivos',
      'es.formats_hint': 'Soportados: .csv, .tsv, .xlsx (presupuesto en formato PBC)',
      'es.classification': 'Capitulo PBC',
      'es.export_format': 'Formato',
      'es.csv_format': 'CSV (compatible con Excel)',
      'es.pbc_detailed': 'PBC Detallado',
      'es.pbc_summary': 'PBC Resumido',
      'es.preview': 'Vista previa',
      'es.positions': 'partidas',
      'es.positions_found': 'partidas encontradas',
      'es.show_less': 'Ver menos',
      'es.show_all': 'Ver todas',
      'es.target_boq': 'Destino de Importacion',
      'es.select_boq': 'Seleccionar Presupuesto',
      'es.importing': 'Importando...',
      'es.import_btn': 'Importar partidas',
      'es.import_failed': 'Fallo en la importacion PBC',
      'es.positions_imported': 'partidas importadas',
      'es.parsed_ok': 'Archivo analizado correctamente',
      'es.parse_error':
        'No se encontraron partidas en el archivo. Asegurese de que el archivo es un presupuesto PBC valido (CSV o Excel).',
      'es.parse_error_generic': 'Error al analizar el archivo PBC.',
      'es.source_boq': '1. Seleccionar Presupuesto a Exportar',
      'es.export_summary': '2. Resumen de Exportacion',
      'es.hide_preview': 'Ocultar vista previa',
      'es.show_preview': 'Mostrar vista previa',
      'es.sections': 'Capitulos',
      'es.format_label': 'Formato',
      'es.prices_label': 'Precios',
      'es.export_btn': 'Exportar como CSV PBC',
      'es.export_failed': 'Fallo en la exportacion PBC',
      'es.no_positions': 'Este presupuesto no tiene partidas para exportar.',
      'es.print_btn': 'Imprimir / PDF',
      'es.trades_ref': 'Referencia de Capitulos PBC',
      'es.with_prices': 'con precios',
      'es.no_prices': 'solo mediciones',
    },
    de: {
      'nav.es_pbc_exchange': 'Spanien PBC Austausch',
      'es.title': 'Spanien PBC / Base de Precios Import / Export',
      'es.subtitle': 'LV-Daten im spanischen PBC-Format austauschen (Excel / CSV)',
      'es.tab_import': 'Importieren',
      'es.tab_export': 'Exportieren',
      'es.import_complete': 'Spanischer PBC-Import abgeschlossen',
      'es.export_complete': 'Spanischer PBC-Export abgeschlossen',
    },
    ru: {
      'nav.es_pbc_exchange': 'Ispanija PBC Obmen',
      'es.title': 'Ispanija PBC / Base de Precios Import / Eksport',
      'es.subtitle': 'Obmen dannymi smety v formate PBC (Excel / CSV)',
      'es.tab_import': 'Import',
      'es.tab_export': 'Eksport',
      'es.import_complete': 'Import PBC zavershen',
      'es.export_complete': 'Eksport PBC zavershen',
    },
  },
};
