import { lazy } from 'react';
import { Landmark } from 'lucide-react';
import type { ModuleManifest } from '../_types';

const PLExchangeModule = lazy(() => import('./PLExchangeModule'));

export const manifest: ModuleManifest = {
  id: 'pl-knr-exchange',
  name: 'Poland KNR Exchange',
  description: 'Import/export BOQs in Polish KNR / KNNR format (Excel/CSV)',
  version: '1.0.0',
  icon: Landmark,
  category: 'regional',
  defaultEnabled: false,
  depends: ['boq'],
  routes: [
    {
      path: '/pl-knr-exchange',
      title: 'Poland KNR Exchange',
      component: PLExchangeModule,
    },
  ],
  // Issue #217 — reached from /boq (regional import/export); no duplicate sidebar entry.
  navItems: [],
  searchEntries: [
    {
      label: 'Poland KNR Import / Export',
      path: '/pl-knr-exchange',
      keywords: [
        'poland',
        'polish',
        'polska',
        'knr',
        'knnr',
        'kosztorys',
        'przedmiar',
        'norma',
        'zuzia',
        'pln',
        'zloty',
      ],
    },
  ],
  translations: {
    en: {
      'nav.pl_knr_exchange': 'Poland KNR Exchange',
      'pl.title': 'Poland KNR Import / Export',
      'pl.subtitle': 'Exchange Bills of Quantities in KNR / KNNR format (Excel / CSV)',
      'pl.tab_import': 'Import',
      'pl.tab_export': 'Export',
      'pl.import_complete': 'Polish KNR BOQ import complete',
      'pl.export_complete': 'Polish KNR BOQ export complete',
      'pl.info': 'KNR (Katalog Naklad\u00f3w Rzeczowych) and KNNR (Kosztorysowe Normy Naklad\u00f3w Rzeczowych) are the Polish standard cost catalogues for construction estimating. Compatible with Norma Pro, Zuzia, Rodos, and other Polish estimating software. Organized by trade sections following Polish construction classification.',
      'pl.drop_file': 'Drop a Polish KNR/KNNR BOQ file here (Excel or CSV), or',
      'pl.browse': 'Browse files',
      'pl.formats_hint': 'Supported: .csv, .tsv, .xlsx (KNR/KNNR-formatted BOQ)',
      'pl.classification': 'KNR Section',
      'pl.export_format': 'Format',
      'pl.csv_format': 'CSV (Excel-compatible)',
      'pl.detailed': 'KNR Detailed',
      'pl.summary': 'KNR Summary',
      'pl.preview': 'Preview',
      'pl.positions': 'positions',
      'pl.positions_found': 'positions found',
      'pl.show_less': 'Show less',
      'pl.show_all': 'Show all',
      'pl.target_boq': 'Import Target',
      'pl.select_boq': 'Select BOQ',
      'pl.importing': 'Importing...',
      'pl.import_btn': 'Import positions',
      'pl.import_failed': 'Polish KNR import failed',
      'pl.positions_imported': 'positions imported',
      'pl.parsed_ok': 'File parsed successfully',
      'pl.parse_error': 'No positions found in the file. Ensure the file is a valid KNR/KNNR-formatted BOQ (CSV, TSV, or XLSX).',
      'pl.parse_error_generic': 'Failed to parse the Polish KNR BOQ file.',
      'pl.source_boq': '1. Select BOQ to Export',
      'pl.export_summary': '2. Export Summary',
      'pl.hide_preview': 'Hide preview',
      'pl.show_preview': 'Show preview',
      'pl.sections': 'Sections',
      'pl.format_label': 'Format',
      'pl.prices_label': 'Prices',
      'pl.export_btn': 'Export as KNR CSV',
      'pl.export_failed': 'Polish KNR export failed',
      'pl.no_positions': 'This BOQ has no positions to export.',
      'pl.print_btn': 'Print / PDF',
      'pl.trades_ref': 'KNR Trade Sections Reference',
      'pl.with_prices': 'with prices',
      'pl.no_prices': 'quantities only',
    },
    pl: {
      'nav.pl_knr_exchange': 'Polska KNR Wymiana',
      'pl.title': 'Polska KNR Import / Eksport',
      'pl.subtitle': 'Wymiana kosztorys\u00f3w w formacie KNR / KNNR (Excel / CSV)',
      'pl.tab_import': 'Importuj',
      'pl.tab_export': 'Eksportuj',
      'pl.import_complete': 'Import kosztorysu KNR zako\u0144czony',
      'pl.export_complete': 'Eksport kosztorysu KNR zako\u0144czony',
      'pl.info': 'KNR (Katalog Nak\u0142ad\u00f3w Rzeczowych) i KNNR (Kosztorysowe Normy Nak\u0142ad\u00f3w Rzeczowych) to polskie standardowe katalogi nak\u0142ad\u00f3w dla kosztorysowania budowlanego. Kompatybilne z Norma Pro, Zuzia, Rodos i innym polskim oprogramowaniem kosztorysowym. Zorganizowane wed\u0142ug bran\u017c zgodnie z polsk\u0105 klasyfikacj\u0105 budowlan\u0105.',
      'pl.drop_file': 'Upu\u015b\u0107 plik kosztorysu KNR/KNNR tutaj (Excel lub CSV), lub',
      'pl.browse': 'Przegl\u0105daj pliki',
      'pl.formats_hint': 'Obs\u0142ugiwane: .csv, .tsv, .xlsx (kosztorys w formacie KNR/KNNR)',
      'pl.classification': 'Bran\u017ca KNR',
      'pl.export_format': 'Format',
      'pl.csv_format': 'CSV (kompatybilny z Excel)',
      'pl.detailed': 'KNR Szczeg\u00f3\u0142owy',
      'pl.summary': 'KNR Uproszczony',
      'pl.preview': 'Podgl\u0105d',
      'pl.positions': 'pozycji',
      'pl.positions_found': 'pozycji znalezionych',
      'pl.show_less': 'Poka\u017c mniej',
      'pl.show_all': 'Poka\u017c wszystko',
      'pl.target_boq': 'Cel importu',
      'pl.select_boq': 'Wybierz kosztorys',
      'pl.importing': 'Importowanie...',
      'pl.import_btn': 'Importuj pozycje',
      'pl.import_failed': 'Import KNR nie powi\u00f3d\u0142 si\u0119',
      'pl.positions_imported': 'pozycji zaimportowanych',
      'pl.parsed_ok': 'Plik przetworzony pomy\u015blnie',
      'pl.parse_error': 'Nie znaleziono pozycji w pliku. Upewnij si\u0119, \u017ce plik jest prawid\u0142owym kosztorysem KNR/KNNR (CSV, TSV lub XLSX).',
      'pl.parse_error_generic': 'Nie uda\u0142o si\u0119 przetworzy\u0107 pliku KNR.',
      'pl.source_boq': '1. Wybierz kosztorys do eksportu',
      'pl.export_summary': '2. Podsumowanie eksportu',
      'pl.hide_preview': 'Ukryj podgl\u0105d',
      'pl.show_preview': 'Poka\u017c podgl\u0105d',
      'pl.sections': 'Sekcje',
      'pl.format_label': 'Format',
      'pl.prices_label': 'Ceny',
      'pl.export_btn': 'Eksportuj jako KNR CSV',
      'pl.export_failed': 'Eksport KNR nie powi\u00f3d\u0142 si\u0119',
      'pl.no_positions': 'Ten kosztorys nie ma pozycji do eksportu.',
      'pl.print_btn': 'Drukuj / PDF',
      'pl.trades_ref': 'Bran\u017ce KNR \u2014 Referencja',
      'pl.with_prices': 'z cenami',
      'pl.no_prices': 'tylko ilo\u015bci',
    },
    de: {
      'nav.pl_knr_exchange': 'Polen KNR Austausch',
      'pl.title': 'Polen KNR Import / Export',
      'pl.subtitle': 'Leistungsverzeichnis im polnischen KNR/KNNR-Format austauschen (Excel / CSV)',
      'pl.tab_import': 'Importieren',
      'pl.tab_export': 'Exportieren',
      'pl.import_complete': 'Polnischer KNR-Import abgeschlossen',
      'pl.export_complete': 'Polnischer KNR-Export abgeschlossen',
    },
    ru: {
      'nav.pl_knr_exchange': 'Pol\'sha KNR Obmen',
      'pl.title': 'Pol\'sha KNR Import / Eksport',
      'pl.subtitle': 'Obmen dannymi smety v formate KNR / KNNR (Excel / CSV)',
      'pl.tab_import': 'Import',
      'pl.tab_export': 'Eksport',
      'pl.import_complete': 'Import KNR zavershen',
      'pl.export_complete': 'Eksport KNR zavershen',
    },
  },
};
