import { lazy } from 'react';
import { Globe } from 'lucide-react';
import type { ModuleManifest } from '../_types';

const BRExchangeModule = lazy(() => import('./BRExchangeModule'));

export const manifest: ModuleManifest = {
  id: 'br-sinapi-exchange',
  name: 'Brazil SINAPI Exchange',
  description: 'Import/export BOQs in SINAPI / TCPO format (Excel/CSV)',
  version: '1.0.0',
  icon: Globe,
  category: 'regional',
  defaultEnabled: false,
  depends: ['boq'],
  routes: [
    {
      path: '/br-sinapi-exchange',
      title: 'Brazil SINAPI Exchange',
      component: BRExchangeModule,
    },
  ],
  // Issue #217 — reached from /boq (regional import/export); no duplicate sidebar entry.
  navItems: [],
  searchEntries: [
    {
      label: 'Brazil SINAPI Import / Export',
      path: '/br-sinapi-exchange',
      keywords: [
        'brazil',
        'brazilian',
        'sinapi',
        'tcpo',
        'bdi',
        'composição',
        'orçamento',
        'caixa',
        'real',
        'brl',
      ],
    },
  ],
  translations: {
    en: {
      'nav.br_sinapi_exchange': 'Brazil SINAPI Exchange',
      'br.title': 'Brazil SINAPI / TCPO Import / Export',
      'br.subtitle': 'Exchange Bills of Quantities in SINAPI / TCPO format (Excel / CSV)',
      'br.tab_import': 'Import',
      'br.tab_export': 'Export',
      'br.import_complete': 'Brazilian SINAPI import complete',
      'br.export_complete': 'Brazilian SINAPI export complete',
      'br.info':
        'SINAPI (Sistema Nacional de Pesquisa de Custos e Indices da Construcao Civil) is the official Brazilian cost reference maintained by Caixa Economica Federal. TCPO (Tabela de Composicoes de Precos para Orcamentos) is the industry-standard composition database by PINI. Compatible with BDI (Bonificacoes e Despesas Indiretas) markup and Brazilian public procurement requirements.',
      'br.drop_file': 'Drop a SINAPI/TCPO BOQ file here (Excel or CSV), or',
      'br.browse': 'Browse files',
      'br.formats_hint': 'Supported: .csv, .tsv, .xlsx (SINAPI/TCPO-formatted BOQ)',
      'br.classification': 'SINAPI Section',
      'br.export_format': 'Format',
      'br.csv_format': 'CSV (Excel-compatible)',
      'br.sinapi_detailed': 'SINAPI Detailed',
      'br.sinapi_summary': 'SINAPI Summary',
      'br.preview': 'Preview',
      'br.positions': 'positions',
      'br.positions_found': 'positions found',
      'br.show_less': 'Show less',
      'br.show_all': 'Show all',
      'br.target_boq': 'Import Target',
      'br.select_boq': 'Select BOQ',
      'br.importing': 'Importing...',
      'br.import_btn': 'Import positions',
      'br.import_failed': 'SINAPI import failed',
      'br.positions_imported': 'positions imported',
      'br.parsed_ok': 'File parsed successfully',
      'br.parse_error':
        'No positions found in the file. Ensure the file is a valid SINAPI/TCPO spreadsheet (CSV or Excel).',
      'br.parse_error_generic': 'Failed to parse the SINAPI/TCPO file.',
      'br.source_boq': '1. Select BOQ to Export',
      'br.export_summary': '2. Export Summary',
      'br.hide_preview': 'Hide preview',
      'br.show_preview': 'Show preview',
      'br.sections': 'Sections',
      'br.format_label': 'Format',
      'br.prices_label': 'Prices',
      'br.export_btn': 'Export as SINAPI CSV',
      'br.export_failed': 'SINAPI export failed',
      'br.no_positions': 'This BOQ has no positions to export.',
      'br.print_btn': 'Print / PDF',
      'br.trades_ref': 'SINAPI Trade Sections Reference',
      'br.with_prices': 'with prices',
      'br.no_prices': 'quantities only',
    },
    pt: {
      'nav.br_sinapi_exchange': 'Troca SINAPI Brasil',
      'br.title': 'SINAPI / TCPO Importar / Exportar',
      'br.subtitle':
        'Troca de quantitativos no formato SINAPI / TCPO (Excel / CSV)',
      'br.tab_import': 'Importar',
      'br.tab_export': 'Exportar',
      'br.import_complete': 'Importacao SINAPI concluida',
      'br.export_complete': 'Exportacao SINAPI concluida',
      'br.info':
        'SINAPI (Sistema Nacional de Pesquisa de Custos e Indices da Construcao Civil) e a referencia oficial de custos brasileira mantida pela Caixa Economica Federal. TCPO (Tabela de Composicoes de Precos para Orcamentos) e o banco de composicoes padrao da industria pela PINI. Compativel com BDI (Bonificacoes e Despesas Indiretas) e requisitos de licitacao publica brasileira.',
      'br.drop_file': 'Solte um arquivo SINAPI/TCPO aqui (Excel ou CSV), ou',
      'br.browse': 'Procurar arquivos',
      'br.formats_hint': 'Suportados: .csv, .tsv, .xlsx (orcamento no formato SINAPI/TCPO)',
      'br.classification': 'Secao SINAPI',
      'br.export_format': 'Formato',
      'br.csv_format': 'CSV (compativel com Excel)',
      'br.sinapi_detailed': 'SINAPI Detalhado',
      'br.sinapi_summary': 'SINAPI Resumido',
      'br.preview': 'Pre-visualizacao',
      'br.positions': 'itens',
      'br.positions_found': 'itens encontrados',
      'br.show_less': 'Mostrar menos',
      'br.show_all': 'Mostrar todos',
      'br.target_boq': 'Destino da Importacao',
      'br.select_boq': 'Selecionar Orcamento',
      'br.importing': 'Importando...',
      'br.import_btn': 'Importar itens',
      'br.import_failed': 'Falha na importacao SINAPI',
      'br.positions_imported': 'itens importados',
      'br.parsed_ok': 'Arquivo analisado com sucesso',
      'br.parse_error':
        'Nenhum item encontrado no arquivo. Verifique se o arquivo e um orcamento SINAPI/TCPO valido (CSV ou Excel).',
      'br.parse_error_generic': 'Falha ao analisar o arquivo SINAPI/TCPO.',
      'br.source_boq': '1. Selecionar Orcamento para Exportar',
      'br.export_summary': '2. Resumo da Exportacao',
      'br.hide_preview': 'Ocultar pre-visualizacao',
      'br.show_preview': 'Mostrar pre-visualizacao',
      'br.sections': 'Secoes',
      'br.format_label': 'Formato',
      'br.prices_label': 'Precos',
      'br.export_btn': 'Exportar como CSV SINAPI',
      'br.export_failed': 'Falha na exportacao SINAPI',
      'br.no_positions': 'Este orcamento nao possui itens para exportar.',
      'br.print_btn': 'Imprimir / PDF',
      'br.trades_ref': 'Referencia de Secoes SINAPI',
      'br.with_prices': 'com precos',
      'br.no_prices': 'somente quantidades',
    },
    de: {
      'nav.br_sinapi_exchange': 'Brasilien SINAPI Austausch',
      'br.title': 'Brasilien SINAPI / TCPO Import / Export',
      'br.subtitle': 'LV-Daten im brasilianischen SINAPI/TCPO-Format austauschen (Excel / CSV)',
      'br.tab_import': 'Importieren',
      'br.tab_export': 'Exportieren',
      'br.import_complete': 'Brasilianischer SINAPI-Import abgeschlossen',
      'br.export_complete': 'Brasilianischer SINAPI-Export abgeschlossen',
    },
    ru: {
      'nav.br_sinapi_exchange': 'Brazilija SINAPI Obmen',
      'br.title': 'Brazilija SINAPI / TCPO Import / Eksport',
      'br.subtitle': 'Obmen dannymi smety v formate SINAPI/TCPO (Excel / CSV)',
      'br.tab_import': 'Import',
      'br.tab_export': 'Eksport',
      'br.import_complete': 'Import SINAPI zavershen',
      'br.export_complete': 'Eksport SINAPI zavershen',
    },
  },
};
