import { lazy } from 'react';
import { Euro } from 'lucide-react';
import type { ModuleManifest } from '../_types';

const DPGFExchangeModule = lazy(() => import('./DPGFExchangeModule'));

export const manifest: ModuleManifest = {
  id: 'fr-dpgf-exchange',
  name: 'France DPGF / DQE Exchange',
  description:
    'Import and export BOQ data in French DPGF/DQE format (Excel/CSV) with Lots techniques',
  version: '1.0.0',
  icon: Euro,
  category: 'regional',
  defaultEnabled: false,
  depends: ['boq'],
  routes: [
    {
      path: '/fr-dpgf-exchange',
      title: 'France DPGF Exchange',
      component: DPGFExchangeModule,
    },
  ],
  // Issue #217 — reached from /boq (regional import/export); no duplicate sidebar entry.
  navItems: [],
  searchEntries: [
    {
      label: 'France DPGF / DQE Import / Export',
      path: '/fr-dpgf-exchange',
      keywords: [
        'france',
        'french',
        'dpgf',
        'dqe',
        'lots',
        'techniques',
        'dtu',
        'cctp',
        'batiprix',
        'devis',
      ],
    },
  ],
  translations: {
    en: {
      'nav.fr_dpgf_exchange': 'France DPGF Exchange',
      'dpgf.title': 'France DPGF / DQE Import / Export',
      'dpgf.subtitle': 'Exchange BOQ data in French DPGF/DQE format with Lots techniques',
      'dpgf.tab_import': 'Import',
      'dpgf.tab_export': 'Export',
      'dpgf.import_complete': 'DPGF import complete',
      'dpgf.export_complete': 'DPGF export complete',
      'dpgf.info':
        'DPGF (Decomposition du Prix Global et Forfaitaire) and DQE (Detail Quantitatif Estimatif) are standard French BOQ formats. Work is organized by Lots techniques (technical trade packages) following NF DTU standards. Compatible with Batiprix, Artisans du Batiment, and French public procurement.',
      'dpgf.drop_file': 'Drop a DPGF/DQE file here (Excel or CSV), or',
      'dpgf.browse': 'Browse files',
      'dpgf.dpgf_format': 'DPGF (Lump Sum)',
      'dpgf.dqe_format': 'DQE (Measured)',
      'dpgf.formats_hint': 'Supported: .csv, .tsv, .xlsx (DPGF/DQE formatted BOQ)',
      'dpgf.preview': 'Preview',
      'dpgf.positions': 'positions',
      'dpgf.positions_found': 'positions found',
      'dpgf.show_less': 'Show less',
      'dpgf.show_all': 'Show all',
      'dpgf.target_boq': 'Import Target',
      'dpgf.select_boq': 'Select BOQ',
      'dpgf.importing': 'Importing...',
      'dpgf.import_btn': 'Import positions',
      'dpgf.import_failed': 'DPGF import failed',
      'dpgf.positions_imported': 'positions imported',
      'dpgf.parsed_ok': 'File parsed successfully',
      'dpgf.parse_error':
        'No positions found in the file. Ensure the file is a valid DPGF/DQE spreadsheet (CSV or Excel).',
      'dpgf.parse_error_generic': 'Failed to parse the DPGF/DQE file.',
      'dpgf.source_boq': '1. Select BOQ to Export',
      'dpgf.export_format': 'Format',
      'dpgf.export_summary': '2. Export Summary',
      'dpgf.hide_preview': 'Hide preview',
      'dpgf.show_preview': 'Show preview',
      'dpgf.sections': 'Sections',
      'dpgf.format_label': 'Format',
      'dpgf.prices': 'Prices',
      'dpgf.export_btn': 'Export as DPGF CSV',
      'dpgf.export_failed': 'DPGF export failed',
      'dpgf.no_positions': 'This BOQ has no positions to export.',
      'dpgf.print_btn': 'Print PDF',
      'dpgf.lot': 'Lot',
    },
    fr: {
      'nav.fr_dpgf_exchange': 'Echange DPGF / DQE',
      'dpgf.title': 'DPGF / DQE Import / Export',
      'dpgf.subtitle': 'Echanger les donnees de chiffrage au format DPGF/DQE avec Lots techniques',
      'dpgf.tab_import': 'Importer',
      'dpgf.tab_export': 'Exporter',
      'dpgf.import_complete': 'Import DPGF termine',
      'dpgf.export_complete': 'Export DPGF termine',
      'dpgf.drop_file': 'Glissez un fichier DPGF/DQE ici (Excel ou CSV), ou',
      'dpgf.browse': 'Parcourir',
      'dpgf.dpgf_format': 'DPGF (Forfait)',
      'dpgf.dqe_format': 'DQE (Metre)',
      'dpgf.info':
        'Le DPGF (Decomposition du Prix Global et Forfaitaire) et le DQE (Detail Quantitatif Estimatif) sont les formats standards francais pour les devis quantitatifs. Les travaux sont organises en Lots techniques suivant les normes NF DTU. Compatible avec Batiprix et les marches publics.',
      'dpgf.formats_hint': 'Formats acceptes : .csv, .tsv, .xlsx (BOQ au format DPGF/DQE)',
      'dpgf.preview': 'Apercu',
      'dpgf.positions': 'postes',
      'dpgf.positions_found': 'postes trouves',
      'dpgf.show_less': 'Voir moins',
      'dpgf.show_all': 'Voir tout',
      'dpgf.target_boq': 'Cible d\'import',
      'dpgf.select_boq': 'Selectionner le DQE',
      'dpgf.importing': 'Import en cours...',
      'dpgf.import_btn': 'Importer les postes',
      'dpgf.import_failed': 'Echec de l\'import DPGF',
      'dpgf.positions_imported': 'postes importes',
      'dpgf.parsed_ok': 'Fichier analyse avec succes',
      'dpgf.parse_error':
        'Aucun poste trouve dans le fichier. Verifiez que le fichier est un DPGF/DQE valide (CSV ou Excel).',
      'dpgf.parse_error_generic': 'Echec de l\'analyse du fichier DPGF/DQE.',
      'dpgf.source_boq': '1. Selectionner le DQE a exporter',
      'dpgf.export_format': 'Format',
      'dpgf.export_summary': '2. Resume de l\'export',
      'dpgf.hide_preview': 'Masquer l\'apercu',
      'dpgf.show_preview': 'Afficher l\'apercu',
      'dpgf.sections': 'Lots',
      'dpgf.format_label': 'Format',
      'dpgf.prices': 'Prix',
      'dpgf.export_btn': 'Exporter en CSV DPGF',
      'dpgf.export_failed': 'Echec de l\'export DPGF',
      'dpgf.no_positions': 'Ce DQE ne contient aucun poste a exporter.',
      'dpgf.print_btn': 'Imprimer PDF',
      'dpgf.lot': 'Lot',
    },
    de: {
      'nav.fr_dpgf_exchange': 'FR DPGF Austausch',
      'dpgf.title': 'Frankreich DPGF / DQE Import / Export',
      'dpgf.subtitle': 'LV-Daten im franzosischen DPGF/DQE-Format austauschen',
      'dpgf.tab_import': 'Importieren',
      'dpgf.tab_export': 'Exportieren',
      'dpgf.import_complete': 'DPGF-Import abgeschlossen',
      'dpgf.export_complete': 'DPGF-Export abgeschlossen',
    },
    ru: {
      'nav.fr_dpgf_exchange': 'FR DPGF Obmen',
      'dpgf.title': 'Franciya DPGF / DQE Import / Eksport',
      'dpgf.subtitle': 'Obmen dannymi smety v formate DPGF/DQE s Lots techniques',
      'dpgf.tab_import': 'Import',
      'dpgf.tab_export': 'Eksport',
      'dpgf.import_complete': 'Import DPGF zavershen',
      'dpgf.export_complete': 'Eksport DPGF zavershen',
    },
  },
};
